/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Resource = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Text,
  'resources' : IDL.Vec(Resource),
  'name' : IDL.Text,
});
export const Semester = IDL.Record({
  'id' : IDL.Text,
  'subjects' : IDL.Vec(Subject),
  'name' : IDL.Text,
});
export const Department = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'semesters' : IDL.Vec(Semester),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDepartment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addSemester' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'editDepartment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'editResource' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'editSemester' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'editSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeDepartment' : IDL.Func([IDL.Text], [], []),
  'removeResource' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'removeSemester' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Resource = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Text,
    'resources' : IDL.Vec(Resource),
    'name' : IDL.Text,
  });
  const Semester = IDL.Record({
    'id' : IDL.Text,
    'subjects' : IDL.Vec(Subject),
    'name' : IDL.Text,
  });
  const Department = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'semesters' : IDL.Vec(Semester),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDepartment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addSemester' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'editDepartment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'editResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'editSemester' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'editSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllDepartments' : IDL.Func([], [IDL.Vec(Department)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeDepartment' : IDL.Func([IDL.Text], [], []),
    'removeResource' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'removeSemester' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };