/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Department {
  'id' : string,
  'name' : string,
  'semesters' : Array<Semester>,
}
export interface Resource { 'id' : bigint, 'url' : string, 'title' : string }
export interface Semester {
  'id' : string,
  'subjects' : Array<Subject>,
  'name' : string,
}
export interface Subject {
  'id' : string,
  'resources' : Array<Resource>,
  'name' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDepartment' : ActorMethod<[string, string], undefined>,
  'addResource' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addSemester' : ActorMethod<[string, string, string], undefined>,
  'addSubject' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'editDepartment' : ActorMethod<[string, string], undefined>,
  'editResource' : ActorMethod<
    [string, string, string, bigint, string, string],
    undefined
  >,
  'editSemester' : ActorMethod<[string, string, string], undefined>,
  'editSubject' : ActorMethod<[string, string, string, string], undefined>,
  'getAllDepartments' : ActorMethod<[], Array<Department>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeDepartment' : ActorMethod<[string], undefined>,
  'removeResource' : ActorMethod<[string, string, string, bigint], undefined>,
  'removeSemester' : ActorMethod<[string, string], undefined>,
  'removeSubject' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];